// dummyData.js

const dummyData = [
  {
    name: 'Alice',
    surName: 'Johnson',
    dateOfBirth: '1987-03-22',
    address: '123 Elm Street',
    city: 'Springfield',
    pincode: '62704',
    phoneNumber: '+1 (555) 987-6543',
    email: 'alice.johnson@example.com',
    password: 'password123',
    confirmPassword: 'password123',
    gender: 'female',
    state: 'Illinois',
    religion: 'Christianity',
    motherTongue: 'English',
    caste: 'Protestant',
    gothram: '',
    familyDetails: 'Close-knit family with supportive values',
    maritalStatus: 'Married',
    height: '5\'7"',
    weight: '135 lbs',
    complexion: 'Fair',
    lifestyle: 'Balanced',
    hobbies: 'Reading, Hiking, Cooking',
    expectations: 'Looking for someone who values family and growth',
    preferences: 'Appreciates honesty and mutual respect',
    familyType: 'Nuclear',
    disability: '',
    highestEducation: 'Masters',
    employedIn: 'Private',
    occupation: 'Marketing Manager',
    annualIncome: '$85,000',
    aboutYourself: 'Enthusiastic professional who enjoys learning new skills and spending time with loved ones.',
    photo: 'alice_johnson_photo.jpg',
  },
  {
    name: 'Bob',
    surName: 'Smith',
    dateOfBirth: '1990-11-05',
    address: '456 Oak Avenue',
    city: 'Mapleton',
    pincode: '84043',
    phoneNumber: '+1 (555) 321-6549',
    email: 'bob.smith@example.com',
    password: 'securePass456',
    confirmPassword: 'securePass456',
    gender: 'male',
    state: 'Utah',
    religion: 'Mormon',
    motherTongue: 'English',
    caste: 'None',
    gothram: '',
    familyDetails: 'Family-oriented with a focus on community',
    maritalStatus: 'Single',
    height: '6\'0"',
    weight: '190 lbs',
    complexion: 'Medium',
    lifestyle: 'Active',
    hobbies: 'Running, Playing Guitar, Traveling',
    expectations: 'Seeking a partner who shares a love for adventure and exploration',
    preferences: 'Enjoys spontaneous activities and outdoor events',
    familyType: 'Nuclear',
    disability: '',
    highestEducation: 'Bachelors',
    employedIn: 'Government',
    occupation: 'Civil Engineer',
    annualIncome: '$95,000',
    aboutYourself: 'A dedicated professional with a passion for the outdoors and community service.',
    photo: 'bob_smith_photo.jpg',
  },
  {
    name: 'Clara',
    surName: 'Brown',
    dateOfBirth: '1983-07-14',
    address: '789 Pine Road',
    city: 'Greenwood',
    pincode: '29646',
    phoneNumber: '+1 (555) 654-3210',
    email: 'clara.brown@example.com',
    password: 'clara2024',
    confirmPassword: 'clara2024',
    gender: 'female',
    state: 'South Carolina',
    religion: 'Buddhism',
    motherTongue: 'Spanish',
    caste: 'None',
    gothram: '',
    familyDetails: 'Caring family with strong cultural ties',
    maritalStatus: 'Divorced',
    height: '5\'6"',
    weight: '145 lbs',
    complexion: 'Olive',
    lifestyle: 'Health-conscious',
    hobbies: 'Yoga, Painting, Gardening',
    expectations: 'Looking for someone who is kind-hearted and values personal growth',
    preferences: 'Open to new experiences and learning',
    familyType: 'Nuclear',
    disability: '',
    highestEducation: 'Doctorate',
    employedIn: 'Private',
    occupation: 'Professor',
    annualIncome: '$105,000',
    aboutYourself: 'Dedicated academic with a love for the arts and a commitment to a balanced lifestyle.',
    photo: 'clara_brown_photo.jpg',
  },
  {
    name: 'David',
    surName: 'Lee',
    dateOfBirth: '1992-12-09',
    address: '321 Maple Street',
    city: 'Seattle',
    pincode: '98101',
    phoneNumber: '+1 (555) 432-1098',
    email: 'david.lee@example.com',
    password: 'david789',
    confirmPassword: 'david789',
    gender: 'male',
    state: 'Washington',
    religion: 'Hinduism',
    motherTongue: 'Hindi',
    caste: 'Vaishya',
    gothram: 'Kashyapa',
    familyDetails: 'Supportive family with a focus on education',
    maritalStatus: 'Single',
    height: '5\'9"',
    weight: '160 lbs',
    complexion: 'Wheatish',
    lifestyle: 'Tech-savvy',
    hobbies: 'Programming, Video Games, Cycling',
    expectations: 'Looking for someone who shares a passion for technology and personal growth',
    preferences: 'Values intellectual conversations and ambition',
    familyType: 'Nuclear',
    disability: '',
    highestEducation: 'Bachelors',
    employedIn: 'Private',
    occupation: 'IT Consultant',
    annualIncome: '$90,000',
    aboutYourself: 'Tech enthusiast with a passion for problem-solving and continuous learning.',
    photo: 'david_lee_photo.jpg',
  }
];

export default dummyData;
