// dummyData.js

const dummydata = [
    {
      profile: 'myself',
      firstName: 'John',
      lastName: 'Doe',
      phoneNumber: '1234567890',
      gender: 'male',
      state: 'California',
      city: 'Los Angeles',
      dateOfBirth: '1990-01-01',
      religion: 'Christianity',
      motherTongue: 'English',
      email: 'john.doe@example.com',
      password: 'password123',
      familyDetails: 'A loving family of four',
      caste: 'Brahmin',
      gothram: 'Gautama',
      dosh: 'Manglik',
      maritalStatus: 'Single',
      height: '5\'10"',
      familyStatus: 'Middle Class',
      familyType: 'Nuclear',
      familyValues: 'Moderate',
      disability: '',
      highestEducation: 'Bachelors',
      employedIn: 'Private',
      occupation: 'Software Engineer',
      annualIncome: '$80,000',
      aboutYourself: 'I am a friendly and outgoing person.',
      photo: null,
    },
    {
      profile: 'daughter',
      firstName: 'Emily',
      lastName: 'Smith',
      phoneNumber: '9876543210',
      gender: 'female',
      state: 'New York',
      city: 'New York City',
      dateOfBirth: '1995-05-15',
      religion: 'Islam',
      motherTongue: 'Arabic',
      email: 'emily.smith@example.com',
      password: 'secret123',
      familyDetails: 'Close-knit family with strong values',
      caste: 'Sunni',
      gothram: '',
      dosh: 'None',
      maritalStatus: 'Single',
      height: '5\'5"',
      familyStatus: 'Upper Middle Class',
      familyType: 'Joint',
      familyValues: 'Traditional',
      disability: '',
      highestEducation: 'Masters',
      employedIn: 'Government',
      occupation: 'Doctor',
      annualIncome: '$100,000',
      aboutYourself: 'Passionate about healthcare and helping others.',
      photo: null,
    },
    {
      profile: 'son',
      firstName: 'Michael',
      lastName: 'Johnson',
      phoneNumber: '5553334444',
      gender: 'male',
      state: 'Texas',
      city: 'Houston',
      dateOfBirth: '1988-08-20',
      religion: 'Hinduism',
      motherTongue: 'Hindi',
      email: 'michael.johnson@example.com',
      password: 'secure456',
      familyDetails: 'Large family with diverse interests',
      caste: 'Kshatriya',
      gothram: 'Vashista',
      dosh: 'Nadi',
      maritalStatus: 'Single',
      height: '6\'2"',
      familyStatus: 'Rich',
      familyType: 'Joint',
      familyValues: 'Orthodox',
      disability: '',
      highestEducation: 'Doctorate',
      employedIn: 'Private',
      occupation: 'Research Scientist',
      annualIncome: '$120,000',
      aboutYourself: 'Curious mind passionate about science and innovation.',
      photo: null,
    },
    // Additional sample data objects
    {
      profile: 'relative',
      firstName: 'Sarah',
      lastName: 'Johnson',
      phoneNumber: '1112223333',
      gender: 'female',
      state: 'Florida',
      city: 'Miami',
      dateOfBirth: '1992-04-12',
      religion: 'Christianity',
      motherTongue: 'English',
      email: 'sarah.johnson@example.com',
      password: 'pass123',
      familyDetails: 'Family-oriented and supportive',
      caste: 'Protestant',
      gothram: '',
      dosh: 'None',
      maritalStatus: 'Single',
      height: '5\'8"',
      familyStatus: 'Middle Class',
      familyType: 'Nuclear',
      familyValues: 'Moderate',
      disability: 'None',
      highestEducation: 'Bachelors',
      employedIn: 'Private',
      occupation: 'Marketing Specialist',
      annualIncome: '$70,000',
      aboutYourself: 'Passionate about creativity and digital marketing.',
      photo: null,
    },
    {
      profile: 'friend',
      firstName: 'Alex',
      lastName: 'Brown',
      phoneNumber: '4445556666',
      gender: 'male',
      state: 'Illinois',
      city: 'Chicago',
      dateOfBirth: '1985-11-30',
      religion: 'Christianity',
      motherTongue: 'English',
      email: 'alex.brown@example.com',
      password: 'securepass',
      familyDetails: 'Loyal and trustworthy friend',
      caste: 'Protestant',
      gothram: '',
      dosh: 'None',
      maritalStatus: 'Single',
      height: '5\'11"',
      familyStatus: 'Upper Middle Class',
      familyType: 'Nuclear',
      familyValues: 'Liberal',
      disability: '',
      highestEducation: 'Masters',
      employedIn: 'Government',
      occupation: 'Policy Analyst',
      annualIncome: '$90,000',
      aboutYourself: 'Passionate about public policy and social justice.',
      photo: null,
    },
    // Add more sample data objects as needed
    
  ];
  
  export default dummydata;
  
  